apiVersion: v1
kind: Service
metadata:
  name: {{ include "nodex.fullname" . }}
  labels:
    {{- include "nodex.labels" . | nindent 4 }}
  {{- with (mergeOverwrite (deepCopy .Values.commonAnnotations) .Values.service.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nodex.selectorLabels" . | nindent 4 }}
