import assert from 'node:assert/strict';
import { expect, type Page } from '@playwright/test';
export const CIRCULAR_SLUGS = ['circular-graph','circular-graph-dense'];
export const CIRCULAR_CONSUMER_SOURCE = `import {useEffect,useState} from 'react';
import {CircularGraph} from './components/nodex/circular-graph/component';
import {CircularGraphDense} from './components/nodex/circular-graph-dense/component';
type Mode='normal'|'revised'|'zero'|'partial'|'invalid'|'single'|'empty';
declare global{interface Window{nodexCircularFixture:{setMode:(mode:Mode)=>void}}}
function Charts({mode,animate}:{mode:Mode;animate:boolean}){const names=['Same','Same','Third'];const values=mode==='zero'?[0,0,0]:mode==='invalid'?[NaN,-1,Infinity]:mode==='partial'?[10,null,0]:mode==='revised'?[40,40,5]:[10,40,5];const count=mode==='empty'?0:mode==='single'?1:3;const ties=count<3?[]:[{source:0,target:1,weeklyThreads:mode==='invalid'?NaN:mode==='zero'?0:5},{source:1,target:2,weeklyThreads:mode==='invalid'?-1:mode==='zero'?0:10},{source:0,target:2,weeklyThreads:null},{source:99,target:0,weeklyThreads:5}];return <><CircularGraph data={names.slice(0,count).map((team,i)=>({team,headcount:values[i]!}))} ties={ties} animate={animate}/><CircularGraphDense data={names.slice(0,count).map((repository,i)=>({repository,organizationIndex:i===2?1:0,contributors:mode==='normal'?[36,9,0][i]!:values[i]!}))} ties={ties.map((tie,i)=>({source:tie.source,target:tie.target,shared:mode==='invalid'?NaN:mode==='zero'?0:i===0?3:i===1?0:-2}))} organizations={['A','B']} animate={animate}/></>;}
export function CircularConsumer({animate}:{animate:boolean}){const[mode,setMode]=useState<Mode>('normal');useEffect(()=>{window.nodexCircularFixture={setMode};},[]);return <><section id="circular-primary" className="w-[660px] space-y-6"><Charts mode={mode} animate={animate}/></section><section id="circular-secondary" className="w-[520px] space-y-6"><Charts mode="normal" animate={false}/></section></>;}
`;
async function setMode(page:Page,mode:string){await page.evaluate(value=>(window as unknown as {nodexCircularFixture:{setMode:(mode:string)=>void}}).nodexCircularFixture.setMode(value),mode);}
export async function checkCircularConsumer(page:Page):Promise<void>{
 const simple=page.locator('#circular-primary [data-nx-chart="circular-graph"]');const dense=page.locator('#circular-primary [data-nx-chart="circular-graph-dense"]');
 await expect(simple.locator('[data-nx-team-mark]')).toHaveCount(3);await expect(simple.locator('[data-nx-tie]')).toHaveCount(2);await expect(simple.locator('[data-nx-unpainted-tie]')).toHaveCount(1);assert(Math.abs(Number(await simple.locator('[data-nx-team-mark="1"]').getAttribute('r'))-12.4)<1e-8);assert(Math.abs(Number(await simple.locator('[data-nx-tie="1"]').getAttribute('stroke-width'))-7)<1e-8);
 await expect(dense.locator('[data-nx-repository-mark]')).toHaveCount(3);await expect(dense.locator('[data-nx-repository-label]')).toHaveCount(1);await expect(dense.locator('[data-nx-tie]')).toHaveCount(2);assert(Math.abs(Number(await dense.locator('[data-nx-repository-mark="0"]').getAttribute('r'))-6.85)<1e-8);assert.equal(Number(await dense.locator('[data-nx-repository-mark="2"]').getAttribute('r')),1.75);assert.equal(Number(await dense.locator('[data-nx-tie="1"]').getAttribute('stroke-width')),0.4);
 for(const [node,mark,key]of [[simple,'team-mark','team'],[dense,'repository-mark','repository']]as const){
  await node.scrollIntoViewIfNeeded();const positions=await node.locator(`[data-nx-${mark}]`).evaluateAll(elements=>elements.map(e=>({x:Number(e.getAttribute('cx')),y:Number(e.getAttribute('cy'))})));const dimensions=await node.locator('svg').evaluate(e=>({width:Number(e.getAttribute('width')),height:Number(e.getAttribute('height'))}));const distances=positions.map(p=>Math.hypot(p.x-dimensions.width/2,p.y-dimensions.height/2));assert(Math.max(...distances)-Math.min(...distances)<1e-5,'Native scales must keep the ring circular');
  await node.locator(`[data-nx-${mark}="0"]`).hover();await expect(node.getByRole('status')).toContainText(key==='team'?'10 people':'36 contributors');await expect(node.locator('[data-nx-tie="0"]')).toHaveAttribute('data-nx-related','true');await expect(node.locator('[data-nx-tie="1"]')).toHaveAttribute('data-nx-related','false');await expect(node.locator(`[data-nx-${key}="2"]`)).toHaveAttribute('data-nx-related','false');
  await page.mouse.move(880,10);await node.locator('svg.recharts-surface').focus();await page.keyboard.press('ArrowLeft');await expect(node.getByRole('status')).toContainText(key==='team'?'5 weekly threads':'3 shared contributors');await page.keyboard.press('ArrowRight');await expect(node.getByRole('status')).toContainText(key==='team'?'10 weekly threads':'0 shared contributors');await page.keyboard.press('ArrowRight');await expect(node.getByRole('status')).toContainText('Unavailable');await page.keyboard.press('ArrowRight');await expect(node.getByRole('status')).toContainText(key==='team'?'10 people':'36 contributors');
  await node.evaluate(e=>{const s=(e as HTMLElement).style;s.setProperty('--nx-ink','#123456');s.setProperty('--nx-type-axis-size','16px');});await expect.poll(()=>node.locator(`[data-nx-${mark}="0"]`).evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(18, 52, 86)');await expect.poll(()=>node.locator(`[data-nx-${key}-label="0"]`).evaluate(e=>getComputedStyle(e).fontSize)).toBe(key==='team'?'19px':'17px');
  const oldRadius=await node.locator(`[data-nx-${mark}="0"]`).getAttribute('r');const oldWidth=dimensions.width;await node.evaluate(e=>{(e as HTMLElement).style.width='340px';});await expect.poll(async()=>Number(await node.locator('svg').getAttribute('width'))).toBeLessThan(oldWidth);assert.equal(await node.locator(`[data-nx-${mark}="0"]`).getAttribute('r'),oldRadius);await node.evaluate(e=>{(e as HTMLElement).style.width='';});await expect.poll(async()=>Number(await node.locator('svg').getAttribute('width'))).toBe(oldWidth);
 }
 assert.notEqual(await page.locator('#circular-secondary [data-nx-team-mark="0"]').evaluate(e=>getComputedStyle(e).fill),'rgb(18, 52, 86)');
 await setMode(page,'revised');await expect.poll(async()=>Number(await simple.locator('[data-nx-team-mark="0"]').getAttribute('r'))).toBe(12.4);
 for(const mode of ['zero','partial','invalid','single','empty']){await setMode(page,mode);if(mode==='empty'){await expect(simple.getByRole('status')).toHaveText('No team network available.');await expect(dense.getByRole('status')).toHaveText('No repository network available.');continue;}if(mode==='zero'){await expect(simple.locator('[data-nx-team-mark]')).toHaveCount(0);await expect(simple.locator('[data-nx-tie]')).toHaveCount(0);await expect(dense.locator('[data-nx-repository-mark]')).toHaveCount(3);await expect(dense.locator('[data-nx-tie]')).toHaveCount(3);}if(mode==='invalid'){await expect(simple.locator('[data-nx-team-mark]')).toHaveCount(0);await expect(dense.locator('[data-nx-repository-mark]')).toHaveCount(0);await expect(dense.locator('[data-nx-tie]')).toHaveCount(0);}if(mode==='partial'){await expect(simple.locator('[data-nx-team-mark]')).toHaveCount(1);await expect(dense.locator('[data-nx-repository-mark]')).toHaveCount(2);}if(mode==='single'){await expect(simple.locator('[data-nx-team-mark]')).toHaveCount(1);await expect(dense.locator('[data-nx-repository-mark]')).toHaveCount(1);}for(const node of [simple,dense])assert.equal(await node.evaluate(e=>/NaN|Infinity/.test(e.innerHTML)),false);}
 await setMode(page,'normal');console.log('Validated diameter-aware circular networks, absolute sizes, native weighted curves, duplicate labels, adjacency, unavailable/zero counts, keyboard observations and independent responsive token scopes.');
}
