import assert from 'node:assert/strict';
import { expect, type Page } from '@playwright/test';
export const FLOW_SLUGS = ['aggregate-sankey'];
export const FLOW_CONSUMER_SOURCE = `import {useEffect,useState} from 'react';
import {AggregateSankey} from './components/nodex/aggregate-sankey/component';
 type Mode='normal'|'revised'|'partial'|'zero'|'single'|'empty'|'invalid';
 declare global {interface Window {nodexFlowFixture:{setMode:(mode:Mode)=>void;setEnabled:(value:boolean)=>void}}}
 function Charts({mode,animate}:{mode:Mode;animate:boolean}){
  const rows=[{channel:'Same',toPlans:mode==='zero'?[0,0]:mode==='invalid'?[NaN,-1]:[mode==='revised'?40:10,0]},{channel:'Same',toPlans:mode==='zero'?[0,0]:mode==='invalid'?[Infinity,1]:mode==='partial'?[20,null]:[20,10]}];
  return <AggregateSankey data={mode==='empty'?[]:mode==='single'?rows.slice(0,1).map(row=>({...row,toPlans:row.toPlans.slice(0,1)})):rows} plans={mode==='single'?['Here']:['Here','There']} animate={animate}/>;
 }
 export function FlowConsumer({animate}:{animate:boolean}){const [mode,setMode]=useState<Mode>('normal');const [enabled,setEnabled]=useState(false);useEffect(()=>{window.nodexFlowFixture={setMode,setEnabled};},[]);return <><section id="flow-primary" className="w-[660px] space-y-6"><Charts mode={mode} animate={animate||enabled}/></section><section id="flow-secondary" className="w-[520px] space-y-6"><Charts mode="normal" animate={false}/></section></>;}
`;
async function setMode(page:Page,mode:string){await page.evaluate(value=>(window as unknown as {nodexFlowFixture:{setMode:(mode:string)=>void}}).nodexFlowFixture.setMode(value),mode);}
export async function checkFlowConsumer(page:Page):Promise<void>{
 const node=page.locator('#flow-primary [data-nx-chart="aggregate-sankey"]');const sibling=page.locator('#flow-secondary [data-nx-chart="aggregate-sankey"]');
 await expect(node.locator('[data-nx-allocation]')).toHaveCount(3);await expect(node.locator('[data-nx-node-block]')).toHaveCount(4);await expect(node.locator('[data-nx-zero-link]')).toHaveCount(1);const thickness=Number(await node.locator('[data-nx-allocation="0-0"]').getAttribute('data-nx-thickness'));assert(Math.abs(Number(await node.locator('[data-nx-allocation="1-0"]').getAttribute('data-nx-thickness'))/thickness-2)<1e-9);await expect.poll(()=>node.locator('[data-nx-node-block="channel-1"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(28, 28, 26)');
 const channelHeight=await node.locator('[data-nx-node-block="channel-1"]').evaluate(e=>(e as SVGGraphicsElement).getBBox().height);const otherHeight=await node.locator('[data-nx-node-block="channel-0"]').evaluate(e=>(e as SVGGraphicsElement).getBBox().height);assert(Math.abs(channelHeight/otherHeight-3)<1e-9);
 await node.scrollIntoViewIfNeeded();await node.locator('[data-nx-node-block="channel-0"]').hover();await expect(node.getByRole('status')).toHaveText('Same — 10 accounts');await expect(node.locator('[data-nx-allocation="0-0"]')).toHaveAttribute('data-nx-related','true');await expect(node.locator('[data-nx-allocation="1-0"]')).toHaveAttribute('data-nx-related','false');await expect(node.locator('[data-nx-flow-node="plan-1"]')).toHaveAttribute('data-nx-related','false');await expect(sibling.getByRole('status')).toHaveCount(0);
 await page.mouse.move(880,10);await node.locator('svg.recharts-surface').focus();await page.keyboard.press('Home');await expect(node.getByRole('status')).toHaveText('Same — 30 accounts');await page.keyboard.press('ArrowRight');await expect(node.getByRole('status')).toHaveText('Same — 10 accounts');await page.keyboard.press('End');await expect(node.getByRole('status')).toHaveText('Same → There — 0 accounts of 40');await page.keyboard.press('ArrowLeft');await expect(node.getByRole('status')).toHaveText('Same → Here — 10 accounts of 40');await page.keyboard.press('Escape');await expect(node.getByRole('status')).toHaveCount(0);
 await node.evaluate(e=>{const s=(e as HTMLElement).style;s.setProperty('--nx-ink','#123456');s.setProperty('--nx-type-axis-size','16px');});await expect.poll(()=>node.locator('[data-nx-allocation="1-0"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(18, 52, 86)');await expect.poll(()=>node.locator('[data-nx-node-label="plan-0"]').evaluate(e=>getComputedStyle(e).fontSize)).toBe('17px');assert.notEqual(await sibling.locator('[data-nx-allocation="1-0"]').evaluate(e=>getComputedStyle(e).fill),'rgb(18, 52, 86)');
 const width=Number(await node.locator('svg').getAttribute('width'));await node.evaluate(e=>{(e as HTMLElement).style.width='340px';});await expect.poll(async()=>Number(await node.locator('svg').getAttribute('width'))).toBeLessThan(width);await node.evaluate(e=>{(e as HTMLElement).style.width='';});await expect.poll(async()=>Number(await node.locator('svg').getAttribute('width'))).toBe(width);
 await setMode(page,'revised');await expect.poll(()=>node.locator('[data-nx-node-block="channel-0"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(18, 52, 86)');await page.mouse.move(880,10);await node.locator('svg.recharts-surface').focus();await page.keyboard.press('Home');await expect(node.getByRole('status')).toHaveText('Same — 40 accounts');await page.keyboard.press('Escape');
 for(const mode of ['zero','single','partial','invalid','empty']){await setMode(page,mode);if(['partial','invalid','empty'].includes(mode))await expect(node.getByRole('status')).toContainText('available');else await expect(node.locator('svg.recharts-surface')).toHaveCount(1);if(mode==='zero'){await expect(node.locator('[data-nx-allocation]')).toHaveCount(0);await expect(node.locator('[data-nx-node-block]')).toHaveCount(0);await expect(node.locator('[data-nx-node-label]')).toHaveCount(4);const x=await node.locator('[data-nx-node-label="plan-0"]').getAttribute('x');assert(Number(x)>Number(await node.locator('[data-nx-node-label="channel-0"]').getAttribute('x')),'Zero-value topology must retain the two columns');await node.locator('svg.recharts-surface').focus();await page.keyboard.press('End');await expect(node.getByRole('status')).toHaveText('Same → There — 0 accounts of 0');await page.keyboard.press('Escape');}if(mode==='single'){await expect(node.locator('[data-nx-allocation]')).toHaveCount(1);await expect(node.locator('[data-nx-node-label]')).toHaveCount(2);}assert.equal(await node.evaluate(e=>/NaN|Infinity/.test(e.innerHTML)),false);}
 await setMode(page,'normal');await page.evaluate(()=>(window as unknown as {nodexFlowFixture:{setEnabled:(value:boolean)=>void}}).nodexFlowFixture.setEnabled(true));await page.emulateMedia({reducedMotion:'no-preference'});await expect(node).toHaveAttribute('data-nx-animated','true');await expect.poll(()=>node.locator('svg').evaluate(e=>getComputedStyle(e).animationName)).toBe('nx-allocation-enter');await node.evaluate(e=>{(e as HTMLElement).style.setProperty('--nx-motion-draw-duration','0ms');});await expect(node).toHaveAttribute('data-nx-animated','false');await expect.poll(()=>node.locator('svg').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');await page.emulateMedia({reducedMotion:'reduce'});await page.evaluate(()=>(window as unknown as {nodexFlowFixture:{setEnabled:(value:boolean)=>void}}).nodexFlowFixture.setEnabled(false));
 await node.evaluate(e=>{(e as HTMLElement).style.removeProperty('--nx-motion-draw-duration');});
 console.log('Validated native weighted Sankey layout, rank tones, filled ribbon area, adjacency inspection, zero topology, keyboard nodes/links, scoped CSS delivery and reduced entry motion.');
}
