import assert from 'node:assert/strict';
import { expect, type Page } from '@playwright/test';
export const HIERARCHY_SLUGS=['tree','nested-treemap'];
export const HIERARCHY_CONSUMER_SOURCE=`import{useEffect,useState}from'react';
import{Tree}from'./components/nodex/tree/component';
import{NestedTreemap}from'./components/nodex/nested-treemap/component';
type Mode='normal'|'revised'|'zero'|'partial'|'invalid'|'single'|'empty';
declare global{interface Window{nodexHierarchyFixture:{setMode:(mode:Mode)=>void}}}
function Charts({mode,animate}:{mode:Mode;animate:boolean}){const count=mode==='empty'?0:mode==='single'?1:2;const values=mode==='zero'?[0,0,0]:mode==='partial'?[30,null,20]:mode==='invalid'?[NaN,-1,Infinity]:[mode==='revised'?60:30,10,20];const data=[{name:'Same',teams:[{name:'Same',hours:values[0]!},{name:'Second',hours:values[1]!}]},{name:'Same',teams:[{name:'Same',hours:values[2]!},{name:'Zero',hours:0}]}].slice(0,count);const areas=[{name:'Same',features:mode==='zero'?[]:['Feature','Feature']},{name:'Same',features:mode==='zero'?[]:['Last']}].slice(0,count);return <><Tree data={areas} root='Caller root' animate={animate}/><NestedTreemap data={data} animate={animate}/></>;}
export function HierarchyConsumer({animate}:{animate:boolean}){const[mode,setMode]=useState<Mode>('normal');useEffect(()=>{window.nodexHierarchyFixture={setMode};},[]);return <><section id='hierarchy-primary' className='w-[660px] space-y-6'><Charts mode={mode} animate={animate}/></section><section id='hierarchy-secondary' className='w-[520px] space-y-6'><Charts mode='normal' animate={false}/></section></>;}
`;
async function setMode(page:Page,mode:string){await page.evaluate(value=>(window as unknown as {nodexHierarchyFixture:{setMode:(mode:string)=>void}}).nodexHierarchyFixture.setMode(value),mode);}
export async function checkHierarchyConsumer(page:Page):Promise<void>{
 const tree=page.locator('#hierarchy-primary [data-nx-chart="tree"]');const map=page.locator('#hierarchy-primary [data-nx-chart="nested-treemap"]');
 await expect(tree.locator('[data-nx-tree-mark]')).toHaveCount(6);await expect(tree.locator('[data-nx-branch]')).toHaveCount(5);await expect(tree.locator('[data-nx-tree-label="root"]')).toHaveText('Caller root');
 const coords=await tree.locator('[data-nx-tree-mark]').evaluateAll(nodes=>Object.fromEntries(nodes.map(n=>[n.getAttribute('data-nx-tree-mark'),{x:Number(n.getAttribute('cx')),y:Number(n.getAttribute('cy')),r:Number(n.getAttribute('r'))}])) as Record<string,{x:number;y:number;r:number}>);assert(Object.values(coords).every(p=>p.r===3.5));assert.equal(coords.root!.x,64);assert(Math.abs((coords['area-0']!.x-coords.root!.x)-(coords['area-0-feature-0']!.x-coords['area-0']!.x))<1e-7);const gap=coords['area-0-feature-1']!.y-coords['area-0-feature-0']!.y;assert(Math.abs((coords['area-1-feature-0']!.y-coords['area-0-feature-1']!.y)/gap-2)<1e-7,'Tidy tree must retain cousin separation');
 await tree.scrollIntoViewIfNeeded();await tree.locator('[data-nx-tree-mark="area-0-feature-1"]').hover();await expect(tree.getByRole('status')).toHaveText('Caller root / Same / Feature');await tree.locator('[data-nx-tree-mark="area-0"]').click();await expect(tree.locator('[data-nx-tree-mark]')).toHaveCount(6);
 await page.mouse.move(880,10);await tree.locator('svg.recharts-surface').focus();await page.keyboard.press('ArrowRight');await expect(tree.getByRole('status')).toHaveText('Caller root / Same');await page.keyboard.press('ArrowLeft');await expect(tree.getByRole('status')).toHaveText('Caller root');await page.keyboard.press('ArrowRight');await expect(tree.getByRole('status')).toHaveText('Caller root / Same');await page.keyboard.press('ArrowRight');await expect(tree.getByRole('status')).toHaveText('Caller root / Same / Feature');
 await expect(map.locator('[data-nx-effort-cell]')).toHaveCount(3);await expect(map.locator('[data-nx-effort-area]')).toHaveCount(2);await expect(map.locator('[data-nx-area-heading="area-0"]')).toHaveText('Same · 67%');await expect(map.locator('[data-nx-area-heading="area-1"]')).toHaveText('Same · 33%');assert.equal(await map.locator('foreignObject').count(),2);const cellsContained=await map.locator('[data-nx-effort-cell]').evaluateAll(cells=>cells.every(cell=>{const box=cell.getBoundingClientRect();const parent=cell.closest('foreignObject')!.getBoundingClientRect();return box.width>0&&box.height>0&&box.left>=parent.left&&box.right<=parent.right&&box.top>=parent.top&&box.bottom<=parent.bottom;}));assert(cellsContained,'Each native child chart must use its own rectangle dimensions');
 await map.scrollIntoViewIfNeeded();await map.locator('[data-nx-effort-cell="area-0-team-0"]').hover();await expect(map.getByRole('status')).toHaveText('Same / Same30 hours · 50.0%');await expect(map.locator('[data-nx-effort-area="area-0"]')).toHaveAttribute('data-nx-related','true');await expect(map.locator('[data-nx-effort-area="area-1"]')).toHaveAttribute('data-nx-related','false');await expect.poll(()=>map.locator('[data-nx-area-frame="area-0"]').evaluate(e=>getComputedStyle(e).stroke)).toBe('rgb(28, 28, 26)');
 await page.mouse.move(880,10);await map.focus();await page.keyboard.press('Home');await expect(map.getByRole('status')).toHaveText('Same40 hours · 66.7%');await page.keyboard.press('ArrowRight');await expect(map.getByRole('status')).toHaveText('Same / Same30 hours · 50.0%');await page.keyboard.press('End');await expect(map.getByRole('status')).toHaveText('Same / Zero0 hours · 0.0%');await page.keyboard.press('Escape');await expect(map.getByRole('status')).toHaveCount(0);
 await tree.evaluate(e=>{const s=(e as HTMLElement).style;s.setProperty('--nx-ink','#123456');s.setProperty('--nx-type-axis-size','16px');s.setProperty('--nx-stroke-mark','0.5px');});await expect.poll(()=>tree.locator('[data-nx-branch="area-0"]').evaluate(e=>getComputedStyle(e).stroke)).toBe('rgb(18, 52, 86)');await expect.poll(()=>tree.locator('[data-nx-branch="area-0"]').evaluate(e=>getComputedStyle(e).strokeWidth)).toBe('0.7px');await expect.poll(()=>tree.locator('[data-nx-tree-label="area-0"]').evaluate(e=>getComputedStyle(e).fontSize)).toBe('20px');
 await map.evaluate(e=>{const s=(e as HTMLElement).style;s.setProperty('--nx-markDeep','#654321');s.setProperty('--nx-type-plotValue-size','34px');});await expect.poll(()=>map.locator('[data-nx-effort-cell="area-0-team-0"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(101, 67, 33)');await expect.poll(()=>map.locator('[data-nx-effort-label="area-0-team-0"]').evaluate(e=>getComputedStyle(e).fontSize)).toBe('24px');assert.notEqual(await page.locator('#hierarchy-secondary [data-nx-effort-cell="area-0-team-0"]').evaluate(e=>getComputedStyle(e).fill),'rgb(101, 67, 33)');
 const originalWidth=Number(await map.locator('svg').first().getAttribute('width'));await map.evaluate(e=>{(e as HTMLElement).style.width='340px';});await expect.poll(async()=>Number(await map.locator('svg').first().getAttribute('width'))).toBeLessThan(originalWidth);await map.evaluate(e=>{(e as HTMLElement).style.width='';});await expect.poll(async()=>Number(await map.locator('svg').first().getAttribute('width'))).toBe(originalWidth);
 const ids=await page.locator('#hierarchy-primary clipPath,#hierarchy-secondary clipPath').evaluateAll(elements=>elements.map(e=>e.id));assert.equal(new Set(ids).size,ids.length,'Delivered nested clipping IDs must remain per instance');
 await setMode(page,'revised');await expect(map.locator('[data-nx-area-heading="area-0"]')).toHaveText('Same · 78%');
 for(const mode of ['zero','partial','invalid','single','empty']){await setMode(page,mode);if(mode==='zero'){await expect(map.locator('[data-nx-effort-cell]')).toHaveCount(0);await expect(map).toContainText('No effort recorded · 0 hours');await map.focus();await page.keyboard.press('End');await expect(map.getByRole('status')).toHaveText('Same / Zero0 hours · 0.0%');await page.keyboard.press('Escape');await expect(tree.locator('[data-nx-tree-mark]')).toHaveCount(3);}if(['partial','invalid','empty'].includes(mode))await expect(map.getByRole('status')).toHaveText('No complete effort hierarchy available.');if(mode==='single'){await expect(map.locator('[data-nx-effort-cell]')).toHaveCount(2);await expect(map.locator('[data-nx-area-heading="area-0"]')).toHaveText('Same · 100%');await expect(tree.locator('[data-nx-tree-mark]')).toHaveCount(4);}if(mode==='empty')await expect(tree.getByRole('status')).toHaveText('No product areas available.');for(const node of [tree,map])assert.equal(await node.evaluate(e=>/NaN|Infinity/.test(e.innerHTML)),false);}
 await setMode(page,'normal');console.log('Validated delivered D3 tidy layout with native scatter, nested native treemap levels, derived effort shares, zero/missing hierarchies, clipping IDs, keyboard ancestry and descendant font/paint/stroke overrides.');
}
