import assert from 'node:assert/strict';
import { expect, type Locator, type Page } from '@playwright/test';
export const MAP_SLUGS=['choropleth-states','choropleth-world'];
export const MAP_CONSUMER_SOURCE=`import{useEffect,useState}from'react';
import{ChoroplethStates}from'./components/nodex/choropleth-states/component';
import{ChoroplethWorld}from'./components/nodex/choropleth-world/component';
type Mode='normal'|'revised'|'zero'|'partial'|'invalid'|'single'|'empty'|'duplicate'|'gap';
declare global{interface Window{nodexMapFixture:{setMode:(mode:Mode)=>void}}}
function Charts({mode,animate}:{mode:Mode;animate:boolean}){const values=mode==='zero'?[0,0,0]:mode==='invalid'?[NaN,-1,Infinity]:mode==='partial'?[null,65,0]:mode==='revised'?[20,38,0]:mode==='gap'?[9.5,20.5,0]:[96,65,0];const states=[{state:'California',signUpsK:values[0]!,annotation:{text:'Caller label'}},{state:'New York',signUpsK:values[1]!},{state:'Alaska',signUpsK:values[2]!},{state:'Alabama',signUpsK:mode==='invalid'?NaN:9}];const world=[{country:'United States',monthlyActivesK:values[0]!,annotation:{text:'Caller label',offset:[0,0] as const}},{country:'India',monthlyActivesK:values[1]!},{country:'Somalia',monthlyActivesK:values[2]!}];return <><ChoroplethStates data={mode==='empty'?[]:mode==='single'?states.slice(0,1):mode==='duplicate'?[states[0]!,states[0]!]:states} animate={animate}/><ChoroplethWorld data={mode==='empty'?[]:mode==='single'?world.slice(0,1):mode==='duplicate'?[world[0]!,world[0]!]:world} animate={animate}/></>;}
export function MapConsumer({animate}:{animate:boolean}){const[mode,setMode]=useState<Mode>('normal');useEffect(()=>{window.nodexMapFixture={setMode};},[]);return <><section id='map-primary' className='w-[660px] space-y-6'><Charts mode={mode} animate={animate}/></section><section id='map-secondary' className='w-[520px] space-y-6'><Charts mode='normal' animate={false}/></section></>;}
`;
async function setMode(page:Page,mode:string){await page.evaluate(value=>(window as unknown as {nodexMapFixture:{setMode:(mode:string)=>void}}).nodexMapFixture.setMode(value),mode);}
async function hoverRegion(page:Page,node:Locator,name:string){await node.scrollIntoViewIfNeeded();const p=await node.locator(`[data-nx-region="${name}"]`).evaluate(e=>{const group=e as SVGGraphicsElement;const svg=group.ownerSVGElement!;const point=svg.createSVGPoint();point.x=Number(group.getAttribute('data-nx-center-x'));point.y=Number(group.getAttribute('data-nx-center-y'));const screen=point.matrixTransform(group.getScreenCTM()!);return {x:screen.x,y:screen.y};});await page.mouse.move(p.x,p.y);}
export async function checkMapConsumer(page:Page):Promise<void>{
 const states=page.locator('#map-primary [data-nx-chart="choropleth-states"]');const world=page.locator('#map-primary [data-nx-chart="choropleth-world"]');
 await expect(states.locator('[data-nx-geography]')).toHaveCount(52);assert((await world.locator('[data-nx-geography]').count())>200);await expect(world.locator('[data-nx-geography="Antarctica"]')).toHaveCount(0);await expect(states.locator('[data-nx-map-label="California"]')).toHaveText('Caller label');
 await expect.poll(()=>states.locator('[data-nx-geography="California"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(28, 28, 26)');await expect.poll(()=>states.locator('[data-nx-geography="Alaska"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(216, 215, 209)');await expect.poll(()=>states.locator('[data-nx-geography="Ohio"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(228, 227, 220)');
 const alaska=states.locator('[data-nx-region="Alaska"]');const california=states.locator('[data-nx-region="California"]');assert(Number(await alaska.getAttribute('data-nx-center-x'))<Number(await california.getAttribute('data-nx-center-x')));assert(Number(await alaska.getAttribute('data-nx-center-y'))>Number(await california.getAttribute('data-nx-center-y')));
 for(const [node,first,second,anchor]of [[states,'Alabama — 9k sign-ups','Alaska — 0k sign-ups','California'],[world,'Somalia — 0k MAU','Liechtenstein — not opened yet','United States']]as const){await node.scrollIntoViewIfNeeded();await page.mouse.move(880,10);await node.locator('svg.recharts-surface').focus();await page.keyboard.press('ArrowLeft');await expect(node.getByRole('status')).toHaveText(first);await page.keyboard.press('ArrowRight');await expect(node.getByRole('status')).toHaveText(second);await hoverRegion(page,node,anchor);await expect(node.getByRole('status')).toContainText('96k');await page.mouse.down();await page.mouse.up();await expect(node.locator(`[data-nx-region="${anchor}"]`)).toHaveAttribute('data-nx-visible','true');
 const band=node.getByRole('button',{name:'≤9k',exact:true});await band.click();await expect(band).toHaveAttribute('aria-pressed','false');await expect(node.locator(`[data-nx-region="${node===states?'Alaska':'Somalia'}"]`)).toHaveAttribute('data-nx-visible','false');await band.press('Space');await expect(band).toHaveAttribute('aria-pressed','true');await page.mouse.move(880,10);await node.locator('svg.recharts-surface').focus();
 await node.evaluate(e=>{const s=(e as HTMLElement).style;s.setProperty('--nx-ink','#123456');s.setProperty('--nx-type-legend-size','12px');s.setProperty('--nx-stroke-mark','0.5px');});await expect.poll(()=>node.locator(`[data-nx-geography="${anchor}"]`).evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(18, 52, 86)');await expect.poll(()=>node.getByRole('button',{name:'65k+',exact:true}).evaluate(e=>getComputedStyle(e).fontSize)).toBe('12px');const width=Number(await node.locator('svg').getAttribute('width'));await node.evaluate(e=>{(e as HTMLElement).style.width='340px';});await expect.poll(async()=>Number(await node.locator('svg').getAttribute('width'))).toBeLessThan(width);await node.evaluate(e=>{(e as HTMLElement).style.width='';});await expect.poll(async()=>Number(await node.locator('svg').getAttribute('width'))).toBe(width);}
 assert.notEqual(await page.locator('#map-secondary [data-nx-geography="California"]').evaluate(e=>getComputedStyle(e).fill),'rgb(18, 52, 86)');await expect(page.locator('#map-secondary').getByRole('button',{name:'≤9k',exact:true}).first()).toHaveAttribute('aria-pressed','true');
 await setMode(page,'revised');await expect.poll(()=>states.locator('[data-nx-geography="California"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(176, 175, 169)');await expect.poll(()=>world.locator('[data-nx-geography="India"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(143, 142, 136)');
 for(const mode of ['gap','partial','zero','single','duplicate','invalid','empty']){await setMode(page,mode);if(['duplicate','invalid','empty'].includes(mode)){for(const node of [states,world])await expect(node.getByRole('status')).toContainText('No unique mapped');continue;}if(mode==='gap'){await expect(california).toHaveAttribute('data-nx-visible','false');await expect(world.locator('[data-nx-region="India"]')).toHaveAttribute('data-nx-visible','false');}if(mode==='partial'){await expect.poll(()=>states.locator('[data-nx-geography="California"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(228, 227, 220)');await expect(states.locator('[data-nx-map-label="California"]')).toHaveCount(0);}if(mode==='zero'){await expect.poll(()=>states.locator('[data-nx-geography="California"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(216, 215, 209)');await expect(california).toHaveAttribute('data-nx-visible','true');}for(const node of [states,world])assert.equal(await node.evaluate(e=>/NaN|Infinity/.test(e.innerHTML)),false);}
 await setMode(page,'normal');console.log('Validated offline vendored geography, native map scales and holes, preserved insets/crop/bands, caller annotations, zero versus missing data, literal fractional gaps, legend toggles, keyboard regions and scoped paint/type/strokes.');
}
