import assert from 'node:assert/strict';
import { expect, type Page } from '@playwright/test';
export const PATH_SLUGS = ['parallel-coords', 'thread-triptych'];
export const PATH_CONSUMER_SOURCE = `import {useEffect,useState} from 'react';
import {ParallelCoords} from './components/nodex/parallel-coords/component';
import {ThreadTriptych} from './components/nodex/thread-triptych/component';
 type Mode='normal'|'revised'|'partial'|'zero'|'single'|'empty'|'invalid'|'outside';
 declare global {interface Window {nodexPathFixture:{setMode:(mode:Mode)=>void}}}
 const dimensions=[{label:'Price',min:0,max:100,scored:false},{label:'Merit',min:0,max:10,scored:true}];
 function Charts({mode,animate}:{mode:Mode;animate:boolean}){
  const products=[{product:'Same',values:mode==='zero'?[0,0]:mode==='invalid'?[NaN,3]:[mode==='revised'?1:90,mode==='outside'?-1:2]},{product:'Winner',values:mode==='zero'?[0,0]:mode==='partial'?[10,null]:mode==='invalid'?[10,Infinity]:[10,8]},{product:'Same',values:mode==='zero'?[0,0]:mode==='invalid'?[10]:[50,5]}];
  const routes=[{sourceIndex:0,processorIndex:1,destinationIndex:0,volumeK:mode==='invalid'?-1:mode==='zero'?0:mode==='revised'?15:10},{sourceIndex:mode==='invalid'?10:1,processorIndex:0,destinationIndex:1,volumeK:mode==='partial'?null:mode==='zero'?0:20}];
  return <><ParallelCoords data={mode==='empty'?[]:mode==='single'?products.slice(0,1):products} dimensions={dimensions} animate={animate}/><ThreadTriptych data={mode==='empty'?[]:mode==='single'?routes.slice(0,1):routes} sources={['Same','Same']} processors={['First','Second']} destinations={['Here','There']} animate={animate}/></>;
 }
 export function PathConsumer({animate}:{animate:boolean}){const [mode,setMode]=useState<Mode>('normal');useEffect(()=>{window.nodexPathFixture={setMode};},[]);return <><section id="path-primary" className="w-[660px] space-y-6"><Charts mode={mode} animate={animate}/></section><section id="path-secondary" className="w-[520px] space-y-6"><Charts mode="normal" animate={false}/></section></>;}
`;
async function setMode(page:Page,mode:string){await page.evaluate(value=>(window as unknown as {nodexPathFixture:{setMode:(mode:string)=>void}}).nodexPathFixture.setMode(value),mode);}
export async function checkPathConsumer(page:Page):Promise<void>{
 const chart=(slug:string,scope='primary')=>page.locator(`#path-${scope} [data-nx-chart="${slug}"]`);const parallel=chart('parallel-coords');const routes=chart('thread-triptych');
 await expect(parallel.locator('[data-nx-product-line]')).toHaveCount(3);await expect(parallel.locator('[data-nx-hero="true"]')).toHaveAttribute('data-nx-product-line','1');await expect(parallel.locator('[data-nx-highlight]')).toContainText('(WINNER)');await expect(parallel.locator('[data-nx-parallel-axis]')).toHaveCount(2);
 await expect(routes.locator('[data-nx-route]')).toHaveCount(2);await expect(routes.locator('[data-nx-pipeline-node]')).toHaveCount(6);await expect(routes.locator('[data-nx-pipeline-label]')).toHaveCount(4);assert.equal((await routes.locator('[data-nx-route="0"]').getAttribute('d'))?.match(/C/g)?.length,2,'One route must traverse its processor as two continuous cubics');
 const firstStroke=await routes.locator('[data-nx-route="0"]').evaluate(e=>parseFloat(getComputedStyle(e).strokeWidth));const secondStroke=await routes.locator('[data-nx-route="1"]').evaluate(e=>parseFloat(getComputedStyle(e).strokeWidth));assert(Math.abs(secondStroke/firstStroke-2)<1e-6,'Route stroke width must encode volume');
 for(const slug of PATH_SLUGS){const node=chart(slug);await node.scrollIntoViewIfNeeded();await page.mouse.move(880,10);await node.locator('svg.recharts-surface').focus();await page.keyboard.press('ArrowLeft');await expect(node.getByRole('status')).toContainText(slug==='parallel-coords'?'Same — Price: 90 · Merit: 2':'Same → Second → Here · 10k ev/day');await page.keyboard.press('ArrowRight');await expect(node.getByRole('status')).toContainText(slug==='parallel-coords'?'Same — Price: 50 · Merit: 5':'Same → First → There · 20k ev/day');await expect(chart(slug,'secondary').getByRole('status')).toHaveCount(0);}
 await parallel.scrollIntoViewIfNeeded();const axis=parallel.locator('[data-nx-axis-brush="1"]');const box=await axis.boundingBox();assert(box);await page.mouse.move(box.x+box.width/2,box.y+box.height*0.15);await page.mouse.down();await page.mouse.move(box.x+box.width/2,box.y+box.height*0.35,{steps:8});await page.mouse.up();await expect(parallel.locator('[data-nx-axis-selection]')).toHaveCount(1);await expect(parallel.locator('[data-nx-product-line="1"]')).toHaveAttribute('data-nx-selected','true');await expect(parallel.locator('[data-nx-product-line="0"]')).toHaveAttribute('data-nx-selected','false');await expect(parallel.locator('[data-nx-product-line="2"]')).toHaveAttribute('data-nx-selected','false');await expect.poll(()=>parallel.locator('[data-nx-product-line="0"]').evaluate(e=>getComputedStyle(e).opacity)).toBe('0.05');await expect(chart('parallel-coords','secondary').locator('[data-nx-axis-selection]')).toHaveCount(0);await parallel.locator('svg.recharts-surface').focus();await page.keyboard.press('Escape');await expect(parallel.locator('[data-nx-axis-selection]')).toHaveCount(0);
 for(const slug of PATH_SLUGS){const node=chart(slug);await node.evaluate(e=>{const s=(e as HTMLElement).style;s.setProperty('--nx-ink','#123456');s.setProperty('--nx-markQuiet','#234567');s.setProperty('--nx-stroke-mark','1.2px');s.setProperty('--nx-type-axis-size','16px');});const width=Number(await node.locator('svg').getAttribute('width'));await node.evaluate(e=>{(e as HTMLElement).style.width='340px';});await expect.poll(async()=>Number(await node.locator('svg').getAttribute('width'))).toBeLessThan(width);await node.evaluate(e=>{(e as HTMLElement).style.width='';});await expect.poll(async()=>Number(await node.locator('svg').getAttribute('width'))).toBe(width);}
 await expect.poll(()=>parallel.locator('[data-nx-hero="true"]').evaluate(e=>getComputedStyle(e).stroke)).toBe('rgb(18, 52, 86)');await expect.poll(()=>routes.locator('[data-nx-route="0"]').evaluate(e=>getComputedStyle(e).strokeWidth)).toBe('1.68px');await expect.poll(()=>routes.locator('[data-nx-pipeline-label="source-0"]').evaluate(e=>getComputedStyle(e).fontSize)).toBe('14px');assert.notEqual(await chart('thread-triptych','secondary').locator('[data-nx-route="0"]').evaluate(e=>getComputedStyle(e).stroke),'rgb(18, 52, 86)');
 await setMode(page,'revised');await expect(parallel.locator('[data-nx-hero="true"]')).toHaveAttribute('data-nx-product-line','1');await expect.poll(()=>routes.locator('[data-nx-route="0"]').evaluate(e=>parseFloat(getComputedStyle(e).strokeWidth))).toBeCloseTo(2.52,6);
 await setMode(page,'partial');await expect(parallel.locator('[data-nx-product-line]')).toHaveCount(2);await expect(parallel.locator('[data-nx-hero="true"]')).toHaveAttribute('data-nx-product-line','2');await expect(routes.locator('[data-nx-route]')).toHaveCount(1);await expect(routes.locator('[data-nx-pipeline-node]')).toHaveCount(6);
 await setMode(page,'outside');await expect(parallel.locator('[data-nx-product-line]')).toHaveCount(3);const below=await parallel.evaluate(e=>{const line=(e.querySelector('[data-nx-product-line="0"]') as SVGGraphicsElement).getBBox();const axis=(e.querySelector('[data-nx-axis-brush="1"]') as SVGGraphicsElement).getBBox();return line.y+line.height>axis.y+axis.height;});assert(below,'An out-of-range value must extrapolate past its fixed reference range');
 for(const mode of ['zero','single','invalid','empty']){await setMode(page,mode);for(const slug of PATH_SLUGS){const node=chart(slug);if(mode==='invalid'||mode==='empty')await expect(node.getByRole('status')).toContainText('available');else await expect(node.locator('svg.recharts-surface')).toHaveCount(1);assert.equal(await node.evaluate(e=>/NaN|Infinity/.test(e.innerHTML)),false);}if(mode==='zero'){await expect(parallel.locator('[data-nx-product-line]')).toHaveCount(3);await expect(routes.locator('[data-nx-route]')).toHaveCount(0);await expect(routes.locator('[data-nx-pipeline-node]')).toHaveCount(6);}if(mode==='single'){await expect(parallel.locator('[data-nx-product-line]')).toHaveCount(1);await expect(routes.locator('[data-nx-route]')).toHaveCount(1);}}
 await setMode(page,'normal');console.log('Validated dimension-specific scoring, fixed-range extrapolation, pointer range filtering and Escape, continuous weighted routes, caller node labels, scoped source delivery and keyboard observations.');
}
