import assert from 'node:assert/strict';
import { expect, type Page } from '@playwright/test';
export const POPULATION_SLUGS = ['cluster-field', 'hourglass-stream', 'stream-ribbon'];
export const POPULATION_CONSUMER_SOURCE = `import {useEffect,useState} from 'react';
import {ClusterField} from './components/nodex/cluster-field/component';
import {HourglassStream} from './components/nodex/hourglass-stream/component';
import {StreamRibbon} from './components/nodex/stream-ribbon/component';
 type Mode='normal'|'revised'|'partial'|'zero'|'single'|'empty'|'invalid';
 declare global {interface Window {nodexPopulationFixture:{setMode:(mode:Mode)=>void}}}
 function Charts({mode,animate}:{mode:Mode;animate:boolean}){
  const islands=[{name:'Same',x:200,y:60,people:mode==='zero'?0:mode==='invalid'?-1:mode==='partial'?null:3,connectedToCore:true},{name:'Same',x:350,y:-50,people:mode==='zero'?0:mode==='invalid'?1.5:mode==='revised'?4:2,connectedToCore:false}];
  const stages=(mode==='empty'?[]:mode==='single'?[400]:mode==='invalid'?[NaN,-1,1.5]:mode==='zero'?[0,0,0]:mode==='partial'?[400,null,90]:[400,mode==='revised'?200:180,90]).map(people=>({stage:'Same',people}));
  const weekly=(base:number)=>(mode==='single'?[base]:mode==='empty'?[]:[base,mode==='partial'?null:base*2,base*3]).map(value=>mode==='zero'?0:mode==='invalid'?NaN:value);
  const surfaces=[{name:'Same',weekly:weekly(mode==='revised'?20:10),tone:'faint' as const},{name:'Same',weekly:weekly(5),tone:'muted' as const},{name:'New',weekly:weekly(2),tone:'ink' as const}];
  return <><ClusterField data={mode==='empty'||mode==='single'?[]:islands} coreContributors={mode==='empty'?null:mode==='invalid'?NaN:mode==='zero'?0:mode==='single'?1:mode==='revised'?7:4} animate={animate}/><HourglassStream data={stages} animate={animate}/><StreamRibbon data={surfaces} weeks={mode==='empty'?[]:mode==='single'?['Same']:['Same','Same','Last']} animate={animate}/></>;
 }
 export function PopulationConsumer({animate}:{animate:boolean}){const [mode,setMode]=useState<Mode>('normal');useEffect(()=>{window.nodexPopulationFixture={setMode};},[]);return <><section id="population-primary" className="w-[660px] space-y-6"><Charts mode={mode} animate={animate}/></section><section id="population-secondary" className="w-[520px] space-y-6"><Charts mode="normal" animate={false}/></section></>;}
`;
async function setMode(page:Page,mode:string){await page.evaluate(value=>(window as unknown as {nodexPopulationFixture:{setMode:(mode:string)=>void}}).nodexPopulationFixture.setMode(value),mode);}
export async function checkPopulationConsumer(page:Page):Promise<void>{
 const chart=(slug:string,scope='primary')=>page.locator(`#population-${scope} [data-nx-chart="${slug}"]`);const field=chart('cluster-field');const funnel=chart('hourglass-stream');const river=chart('stream-ribbon');
 await expect(field.locator('[data-nx-contributor]')).toHaveCount(9);await expect(field.locator('[data-nx-core-spoke]')).toHaveCount(4);await expect(field.locator('[data-nx-contribution-bridge]')).toHaveCount(1);await expect(field.locator('[data-nx-island-label]')).toHaveCount(2);
 await expect(funnel.locator('[data-nx-population-tick]')).toHaveCount(17);await expect(funnel.locator('[data-nx-population-tick][data-nx-stage="1"]')).toHaveCount(5);await expect(funnel.locator('[data-nx-through="0"]')).toContainText('45%');await expect(funnel.locator('[data-nx-through="1"]')).toContainText('50%');await expect(funnel.locator('[data-nx-funnel-thread]')).toHaveCount(68);
 await expect(river.locator('.recharts-area-area')).toHaveCount(3);await expect(river.locator('.recharts-xAxis .recharts-cartesian-axis-tick-line')).toHaveCount(1);const original=await river.locator('.recharts-area-area[fill="var(--nx-ink)"]').getAttribute('d');
 for(const slug of POPULATION_SLUGS){const node=chart(slug);await node.scrollIntoViewIfNeeded();await page.mouse.move(880,10);await node.locator('svg.recharts-surface').focus();await page.keyboard.press('ArrowLeft');await expect(node.getByRole('status')).toContainText(slug==='cluster-field'?'a core contributor':slug==='hourglass-stream'?'Same — 400':'Same — Same: 10 · Same: 5 · New: 2 · Total: 17');await page.keyboard.press('ArrowRight');await expect(node.getByRole('status')).toContainText(slug==='cluster-field'?'a core contributor':slug==='hourglass-stream'?'Same — 180':'Same — Same: 20 · Same: 10 · New: 4 · Total: 34');await expect(chart(slug,'secondary').getByRole('status')).toHaveCount(0);
  await node.evaluate(e=>{const s=(e as HTMLElement).style;s.setProperty('--nx-ink','#123456');s.setProperty('--nx-bg','#eeddcc');s.setProperty('--nx-markQuiet','#234567');s.setProperty('--nx-stroke-mark','1.2px');s.setProperty('--nx-type-plotValue-size','34px');});const width=Number(await node.locator('svg').getAttribute('width'));await node.evaluate(e=>{(e as HTMLElement).style.width='340px';});await expect.poll(async()=>Number(await node.locator('svg').getAttribute('width'))).toBeLessThan(width);await node.evaluate(e=>{(e as HTMLElement).style.width='';});await expect.poll(async()=>Number(await node.locator('svg').getAttribute('width'))).toBe(width);
 }
 await expect.poll(()=>field.locator('[data-nx-contributor="core-0"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(18, 52, 86)');await expect.poll(()=>funnel.locator('[data-nx-population-tick]').first().evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(18, 52, 86)');await expect.poll(()=>funnel.locator('[data-nx-funnel-thread]').first().evaluate(e=>getComputedStyle(e).stroke)).toBe('rgb(35, 69, 103)');await expect.poll(()=>funnel.locator('[data-nx-stage-count="0"]').evaluate(e=>getComputedStyle(e).fontSize)).toBe('19px');await expect.poll(()=>river.locator('.recharts-area-area[fill="var(--nx-ink)"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(18, 52, 86)');await expect.poll(()=>river.locator('.recharts-area-curve').first().evaluate(e=>getComputedStyle(e).stroke)).toBe('rgb(238, 221, 204)');assert.notEqual(await chart('cluster-field','secondary').locator('[data-nx-contributor="core-0"]').evaluate(e=>getComputedStyle(e).fill),'rgb(18, 52, 86)');
 await setMode(page,'revised');await expect(field.locator('[data-nx-contributor]')).toHaveCount(14);await expect(funnel.locator('[data-nx-through="0"]')).toContainText('50%');await expect(river.locator('.recharts-area-area[fill="var(--nx-ink)"]')).not.toHaveAttribute('d',original!);
 await setMode(page,'partial');await expect(field.locator('[data-nx-contributor]')).toHaveCount(6);await expect(field.locator('[data-nx-island-label="0"]')).toHaveText('Same —');await expect(field.locator('[data-nx-contribution-bridge]')).toHaveCount(0);await expect(funnel.locator('[data-nx-funnel-thread]')).toHaveCount(0);await expect(funnel.locator('[data-nx-stage-count="1"]')).toHaveText('—');for(const path of await river.locator('.recharts-area-area').all()){const d=await path.getAttribute('d');assert.equal(d?.match(/M/g)?.length,2,'An incomplete weekly stack must leave a gap in every band');}
 for(const mode of ['zero','single','invalid','empty']){await setMode(page,mode);for(const slug of POPULATION_SLUGS){const node=chart(slug);if(mode==='invalid'||mode==='empty')await expect(node.getByRole('status')).toContainText('available');else await expect(node.locator('svg.recharts-surface')).toHaveCount(1);assert.equal(await node.evaluate(e=>/NaN|Infinity/.test(e.innerHTML)),false);}if(mode==='zero'){await expect(field.locator('[data-nx-contributor]')).toHaveCount(0);await expect(funnel.locator('[data-nx-population-tick]')).toHaveCount(0);await expect(funnel.locator('[data-nx-through="0"]')).toHaveText('—GET THROUGH');await expect(funnel.locator('[data-nx-funnel-thread]')).toHaveCount(0);}if(mode==='single'){await expect(field.locator('[data-nx-contributor]')).toHaveCount(1);await expect(funnel.locator('[data-nx-stage-label]')).toHaveCount(1);}}
 await setMode(page,'normal');console.log('Validated one-person marks and explicit membership bridges, calibrated funnel ticks and exact conversion rates, native stacked accounts with whole-week gaps, scoped paint/type/strokes and keyboard data.');
}
