import assert from 'node:assert/strict';
import { expect, type Page } from '@playwright/test';
export const RADIAL_SLUGS = ['radial-patchwork', 'radial-convergence'];
export const RADIAL_CONSUMER_SOURCE = `import {useEffect,useState} from 'react';
import {RadialPatchwork} from './components/nodex/radial-patchwork/component';
import {RadialConvergence} from './components/nodex/radial-convergence/component';
 type Mode='normal'|'revised'|'partial'|'zero'|'single'|'empty'|'invalid'|'duplicate';
 declare global {interface Window {nodexRadialFixture:{setMode:(mode:Mode)=>void}}}
 function Charts({mode,animate}:{mode:Mode;animate:boolean}){
  const themes=[{id:'a',name:'Same',degrees:90},{id:mode==='duplicate'?'a':'b',name:'Same',degrees:mode==='invalid'?NaN:-90}];
  const requests=Array.from({length:mode==='single'?1:5},(_,i)=>({id:'R-'+i,themeId:mode==='zero'?null:mode==='partial'&&i<2?'absent':mode==='revised'?'b':i<4?'a':'b'}));
  const deploys=[{hour:mode==='invalid'?24:6,spanDegrees:30,filesTouched:mode==='zero'?0:mode==='revised'?540:360,paged:false},{hour:12,spanDegrees:mode==='invalid'?-1:mode==='zero'?0:60,filesTouched:mode==='partial'?null:720,paged:true}];
  return <><RadialPatchwork data={mode==='empty'?[]:mode==='single'?deploys.slice(0,1):deploys} animate={animate}/><RadialConvergence data={mode==='empty'?[]:requests} themes={themes} animate={animate}/></>;
 }
 export function RadialConsumer({animate}:{animate:boolean}){const [mode,setMode]=useState<Mode>('normal');useEffect(()=>{window.nodexRadialFixture={setMode};},[]);return <><section id="radial-primary" className="w-[660px] space-y-6"><Charts mode={mode} animate={animate}/></section><section id="radial-secondary" className="w-[520px] space-y-6"><Charts mode="normal" animate={false}/></section></>;}
`;
async function setMode(page:Page,mode:string){await page.evaluate(value=>(window as unknown as {nodexRadialFixture:{setMode:(mode:string)=>void}}).nodexRadialFixture.setMode(value),mode);}
export async function checkRadialConsumer(page:Page):Promise<void>{
 const chart=(slug:string,scope='primary')=>page.locator(`#radial-${scope} [data-nx-chart="${slug}"]`);const dial=chart('radial-patchwork');const network=chart('radial-convergence');
 await expect(dial.locator('[data-nx-deploy]')).toHaveCount(2);await expect(dial.locator('[data-nx-clock-tick]')).toHaveCount(96);await expect(dial.locator('[data-nx-clock-label]')).toHaveCount(4);await expect(dial.locator('[data-nx-deploy="0"]')).toHaveAttribute('data-nx-angle','0');await expect(dial.locator('[data-nx-deploy="1"]')).toHaveAttribute('data-nx-span','60');
 const radius=Number(await dial.locator('[data-nx-deploy="0"]').getAttribute('data-nx-radius'));assert(Math.abs(Number(await dial.locator('[data-nx-deploy="1"]').getAttribute('data-nx-radius'))/radius-2)<1e-9);await expect.poll(()=>dial.locator('[data-nx-incident="true"]').evaluate(e=>getComputedStyle(e).fill)).toBe('none');
 await expect(network.locator('[data-nx-node-kind="request"]')).toHaveCount(5);await expect(network.locator('[data-nx-request-link]')).toHaveCount(5);const a=Number(await network.locator('[data-nx-node="a"]').getAttribute('r'));const b=Number(await network.locator('[data-nx-node="b"]').getAttribute('r'));assert(Math.abs(a*a/(b*b)-4)<1e-9,'Hub area must count assigned requests');
 for(const slug of RADIAL_SLUGS){const node=chart(slug);await node.scrollIntoViewIfNeeded();await page.mouse.move(880,10);await node.locator('svg.recharts-surface').focus();await page.keyboard.press('ArrowLeft');await expect(node.getByRole('status')).toContainText(slug==='radial-patchwork'?'deploy #1 — 06:00 · 360 files':'R-0 — Same');await page.keyboard.press('ArrowRight');await expect(node.getByRole('status')).toContainText(slug==='radial-patchwork'?'triggered an incident':'R-1 — Same');await expect(chart(slug,'secondary').getByRole('status')).toHaveCount(0);
  await node.evaluate(e=>{const s=(e as HTMLElement).style;s.setProperty('--nx-ink','#123456');s.setProperty('--nx-stroke-emphasis','1.3px');s.setProperty('--nx-stroke-hairline','1.2px');s.setProperty('--nx-type-axis-size','16px');});
  const width=Number(await node.locator('svg').getAttribute('width'));await node.evaluate(e=>{(e as HTMLElement).style.width='340px';});await expect.poll(async()=>Number(await node.locator('svg').getAttribute('width'))).toBeLessThan(width);await node.evaluate(e=>{(e as HTMLElement).style.width='';});await expect.poll(async()=>Number(await node.locator('svg').getAttribute('width'))).toBe(width);
 }
 await expect.poll(()=>dial.locator('[data-nx-incident="true"]').evaluate(e=>getComputedStyle(e).strokeWidth)).toBe('1.3px');await expect.poll(()=>dial.locator('[data-nx-incident="false"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(18, 52, 86)');await expect.poll(()=>network.locator('[data-nx-node="a"]').evaluate(e=>getComputedStyle(e).fill)).toBe('rgb(18, 52, 86)');await expect.poll(()=>network.locator('[data-nx-request-link]').first().evaluate(e=>getComputedStyle(e).strokeWidth)).toBe('1.2px');await expect.poll(()=>network.locator('[data-nx-theme-label]').first().evaluate(e=>getComputedStyle(e).fontSize)).toBe('16px');assert.notEqual(await chart('radial-convergence','secondary').locator('[data-nx-node="a"]').evaluate(e=>getComputedStyle(e).fill),'rgb(18, 52, 86)');
 await setMode(page,'revised');
 // The fixture setter queues React work; wait for the revised SVG before comparing geometry.
 await expect.poll(async()=>Math.abs(Number(await dial.locator('[data-nx-deploy="0"]').getAttribute('data-nx-radius'))/radius-1.5)).toBeLessThan(0.001);
 await expect(network.locator('[data-nx-node="a"]')).toHaveCount(0);await expect(network.locator('[data-nx-theme-label="a"]')).toHaveText('Same · 0');await expect(network.locator('[data-nx-node="b"]')).toHaveAttribute('data-nx-count','5');
 await setMode(page,'partial');await expect(dial.locator('[data-nx-deploy]')).toHaveCount(1);await expect(network.locator('[data-nx-node-kind="request"]')).toHaveCount(5);await expect(network.locator('[data-nx-request-link]')).toHaveCount(3);await expect(network.locator('[data-nx-node="a"]')).toHaveAttribute('data-nx-count','2');
 for(const mode of ['zero','single','invalid','empty','duplicate']){await setMode(page,mode);for(const slug of RADIAL_SLUGS){const node=chart(slug);if(mode==='invalid'||mode==='empty'||mode==='duplicate'&&slug==='radial-convergence')await expect(node.getByRole('status')).toContainText('available');else await expect(node.locator('svg.recharts-surface')).toHaveCount(1);assert.equal(await node.evaluate(e=>/NaN|Infinity/.test(e.innerHTML)),false);}if(mode==='zero'){await expect(dial.locator('[data-nx-deploy]')).toHaveCount(0);await expect(network.locator('[data-nx-node-kind="theme"]')).toHaveCount(0);await expect(network.locator('[data-nx-request-link]')).toHaveCount(0);}if(mode==='single'){await expect(dial.locator('[data-nx-deploy]')).toHaveCount(1);await expect(network.locator('[data-nx-node-kind="request"]')).toHaveCount(1);}}
 await setMode(page,'normal');console.log('Validated radial time/window/reach, incident outlines, caller-owned request links, hub-area counts, unavailable assignments, scoped guides and keyboard observations.');
}
